### ISSUE TITLE
IndexError: list index out of range when trying to build

### ISSUE THREAD

**Issue by grandrew** [dephell/dephell_discover#12]
```
$ dephell project build --from pyproject.toml --traceback
WARNING cannot find tool.dephell section in the config (path=pyproject.toml)
INFO dumping... (format=setuppy)
INFO dumping... (format=egginfo)
INFO dumping... (format=sdist)
ERROR IndexError: list index out of range 

Traceback (most recent call last):
  File "/usr/local/lib/python3.7/dist-packages/dephell/cli.py", line 115, in main
    result = task()
  File "/usr/local/lib/python3.7/dist-packages/dephell/commands/project_build.py", line 63, in __call__
    project=resolver.graph.metainfo,
  File "/usr/local/lib/python3.7/dist-packages/dephell/converters/sdist.py", line 127, in dump
    self._write_additional_files(tar=tar, project=project, subdir=subdir)
  File "/usr/local/lib/python3.7/dist-packages/dephell/converters/sdist.py", line 179, in _write_additional_files
    package_size = get_path_size(path=project.package.packages[0].path)
IndexError: list index out of range
```
experienced this with 3 of 3 projects that I manage with poetry

**Comment by orsinium** [comment]
Add steps to reproduce, please. Is it open source project? Can you show the files tree?

**Comment by Viginox** [comment]
This issue occurs, when only the `tests` folder could be found but no packages. There is no check if a package could be found after the check for the `tests` folder succeeded.

This issue comes from the **dephell** project and not from dephell_discover.
I will check the issues there and update / create a one for that.
